### ISSUE TITLE
add support for Tag 86

### ISSUE THREAD

**Issue by sivanbecker** [ministryofjustice/mt940-writer#11]
<img width="651" alt="image" src="https://github.com/ministryofjustice/mt940-writer/assets/20453622/fb184e68-7eaf-4b13-89c4-f6075d2f28b8">

<img width="474" alt="image" src="https://github.com/ministryofjustice/mt940-writer/assets/20453622/6e08494e-b5f5-41f5-8c97-50de4b552165">

**Comment by ushkarev** [comment]
Released: https://pypi.org/project/mt940-writer/0.7/
